In [18]:
#importing the libraries 
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [19]:
#import dataset 
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset[['CreditScore','Geography','Gender','Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary']]
#X = dataset.iloc[:, [3,13]].values  
y = dataset.iloc[:, 13].values # to pick the purchase column as the target
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [20]:
X = pd.get_dummies(X)
X.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,1,0

In [21]:
#Split the dataset 
from sklearn.cross_validation import train_test_split 
train_X , test_X, train_y, test_y = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [22]:
from sklearn.preprocessing import StandardScaler
Scale_X = StandardScaler()
train_X = Scale_X.fit_transform(train_X)
test_X = Scale_X.transform(test_X)

In [28]:
#importing Keras Librarries
import keras 
from keras.models import  Sequential
from keras.layers import Dense #initialize weight

#create model
nn_classifier =  Sequential()

#create the input layer and first hidden layer 
nn_classifier.add(Dense(units = 6,kernel_initializer = "uniform", activation = "relu",input_dim = 13))

#create the  second hidden layer 
nn_classifier.add(Dense(units = 6,kernel_initializer = "uniform", activation = "relu"))

#create the  output layer 
nn_classifier.add(Dense(units = 1,kernel_initializer = "uniform", activation = "sigmoid"))

#compiling model

nn_classifier.compile(optimizer ='adam',loss = 'binary_crossentropy', metrics=['accuracy'])

In [29]:
#fit and train the model
nn_classifier.fit(train_X,train_y,batch_size = 10, epochs = 100)

Epoch 1/100
7500/7500 [==============================] - 3s 375us/step - loss: 0.4938 - acc: 0.7955
Epoch 2/100
7500/7500 [==============================] - ETA: 0s - loss: 0.4279 - acc: 0.804 - 1s 165us/step - loss: 0.4278 - acc: 0.8051
Epoch 3/100
7500/7500 [==============================] - ETA: 0s - loss: 0.4233 - acc: 0.818 - 1s 164us/step - loss: 0.4227 - acc: 0.8177
Epoch 4/100
7500/7500 [==============================] - 1s 155us/step - loss: 0.4195 - acc: 0.8229
Epoch 5/100
7500/7500 [==============================] - 1s 163us/step - loss: 0.4152 - acc: 0.8253
Epoch 6/100
7500/7500 [==============================] - 1s 161us/step - loss: 0.4112 - acc: 0.8307
Epoch 7/100
7500/7500 [==============================] - 1s 162us/step - loss: 0.4081 - acc: 0.8320
Epoch 8/100
7500/7500 [==============================] - 1s 164us/step - loss: 0.4058 - acc: 0.8344
Epoch 9/100
7500/7500 [==============================] - 1s 153us/step - loss: 0.4043 - acc: 0.8327
Epoch 10/100
7500/7500 [==============================] - 1s 161us/step - loss: 0.4036 - acc: 0.8331
Epoch 11/100
7500/7500 [==============================] - 1s 181us/step - loss: 0.4026 - acc: 0.8333
Epoch 12/100
7500/7500 [==============================] - 1s 160us/step - loss: 0.4019 - acc: 0.8329
Epoch 13/100
7500/7500 [==============================] - 1s 160us/step - loss: 0.4020 - acc: 0.8331
Epoch 14/100
7500/7500 [==============================] - 1s 154us/step - loss: 0.4013 - acc: 0.8364
Epoch 15/100
7500/7500 [==============================] - 1s 160us/step - loss: 0.4010 - acc: 0.8344
Epoch 16/100
7500/7500 [==============================] - 1s 159us/step - loss: 0.4012 - acc: 0.8359
Epoch 17/100
7500/7500 [==============================] - 1s 156us/step - loss: 0.4003 - acc: 0.8343
Epoch 18/100
7500/7500 [==============================] - 1s 157us/step - loss: 0.4003 - acc: 0.8360 1s - loss:
Epoch 19/100
7500/7500 [==============================] - 1s 163us/step - loss: 0.4001 - acc: 0.8364
Epoch 20/100
7500/7500 [==============================] - 1s 154us/step - loss: 0.3996 - acc: 0.8356
Epoch 21/100
7500/7500 [==============================] - 1s 155us/step - loss: 0.3992 - acc: 0.8363
Epoch 22/100
7500/7500 [==============================] - 1s 156us/step - loss: 0.3992 - acc: 0.8351
Epoch 23/100
7500/7500 [==============================] - 1s 156us/step - loss: 0.3987 - acc: 0.8376
Epoch 24/100
7500/7500 [==============================] - 1s 155us/step - loss: 0.3983 - acc: 0.8359
Epoch 25/100
7500/7500 [==============================] - 1s 154us/step - loss: 0.3987 - acc: 0.8359
Epoch 26/100
7500/7500 [==============================] - 1s 153us/step - loss: 0.3976 - acc: 0.8355
Epoch 27/100
7500/7500 [==============================] - 1s 152us/step - loss: 0.3980 - acc: 0.8348
Epoch 28/100
7500/7500 [==============================] - 1s 158us/step - loss: 0.3980 - acc: 0.8344
Epoch 29/100
7500/7500 [==============================] - 1s 156us/step - loss: 0.3978 - acc: 0.8351
Epoch 30/100
7500/7500 [==============================] - 1s 155us/step - loss: 0.3974 - acc: 0.8360
Epoch 31/100
7500/7500 [==============================] - 1s 155us/step - loss: 0.3967 - acc: 0.8337
Epoch 32/100
7500/7500 [==============================] - 1s 157us/step - loss: 0.3969 - acc: 0.8372
Epoch 33/100
7500/7500 [==============================] - 1s 157us/step - loss: 0.3967 - acc: 0.8353
Epoch 34/100
7500/7500 [==============================] - 1s 151us/step - loss: 0.3961 - acc: 0.8363
Epoch 35/100
7500/7500 [==============================] - 1s 148us/step - loss: 0.3970 - acc: 0.8369
Epoch 36/100
7500/7500 [==============================] - 1s 155us/step - loss: 0.3963 - acc: 0.8372
Epoch 37/100
7500/7500 [==============================] - 1s 156us/step - loss: 0.3962 - acc: 0.8360
Epoch 38/100
7500/7500 [==============================] - 1s 154us/step - loss: 0.3960 - acc: 0.8377
Epoch 39/100
7500/7500 [==============================] - 1s 154us/step - loss: 0.3958 - acc: 0.8351
Epoch 40/100
7500/7500 [==============================] - 1s 147us/step - loss: 0.3962 - acc: 0.8363
Epoch 41/100
7500/7500 [==============================] - 1s 147us/step - loss: 0.3952 - acc: 0.8372
Epoch 42/100
7500/7500 [==============================] - 1s 155us/step - loss: 0.3953 - acc: 0.8373
Epoch 43/100
7500/7500 [==============================] - 1s 156us/step - loss: 0.3949 - acc: 0.8369
Epoch 44/100
7500/7500 [==============================] - 1s 153us/step - loss: 0.3944 - acc: 0.8372
Epoch 45/100
7500/7500 [==============================] - 1s 152us/step - loss: 0.3946 - acc: 0.8365
Epoch 46/100
7500/7500 [==============================] - 1s 154us/step - loss: 0.3940 - acc: 0.8367
Epoch 47/100
7500/7500 [==============================] - 1s 146us/step - loss: 0.3935 - acc: 0.8367
Epoch 48/100
7500/7500 [==============================] - 1s 153us/step - loss: 0.3921 - acc: 0.8371
Epoch 49/100
7500/7500 [==============================] - 1s 148us/step - loss: 0.3910 - acc: 0.8375
Epoch 50/100
7500/7500 [==============================] - 1s 150us/step - loss: 0.3905 - acc: 0.8389
Epoch 51/100
7500/7500 [==============================] - 1s 154us/step - loss: 0.3871 - acc: 0.8399
Epoch 52/100
7500/7500 [==============================] - 1s 150us/step - loss: 0.3847 - acc: 0.8388
Epoch 53/100
7500/7500 [==============================] - 1s 143us/step - loss: 0.3828 - acc: 0.8397
Epoch 54/100
7500/7500 [==============================] - 1s 150us/step - loss: 0.3801 - acc: 0.8393
Epoch 55/100
7500/7500 [==============================] - 1s 148us/step - loss: 0.3782 - acc: 0.8412
Epoch 56/100
7500/7500 [==============================] - 1s 143us/step - loss: 0.3768 - acc: 0.8411
Epoch 57/100
7500/7500 [==============================] - 1s 147us/step - loss: 0.3750 - acc: 0.8416
Epoch 58/100
7500/7500 [==============================] - 1s 144us/step - loss: 0.3744 - acc: 0.8417
Epoch 59/100
7500/7500 [==============================] - 1s 143us/step - loss: 0.3730 - acc: 0.8412
Epoch 60/100
7500/7500 [==============================] - 1s 143us/step - loss: 0.3711 - acc: 0.8433
Epoch 61/100
7500/7500 [==============================] - 1s 146us/step - loss: 0.3699 - acc: 0.8431
Epoch 62/100
7500/7500 [==============================] - 1s 149us/step - loss: 0.3697 - acc: 0.8435
Epoch 63/100
7500/7500 [==============================] - 1s 140us/step - loss: 0.3681 - acc: 0.8424
Epoch 64/100
7500/7500 [==============================] - 1s 144us/step - loss: 0.3671 - acc: 0.8425
Epoch 65/100
7500/7500 [==============================] - 1s 147us/step - loss: 0.3672 - acc: 0.8431
Epoch 66/100
7500/7500 [==============================] - 1s 141us/step - loss: 0.3656 - acc: 0.8437
Epoch 67/100
7500/7500 [==============================] - 1s 140us/step - loss: 0.3652 - acc: 0.8427
Epoch 68/100
7500/7500 [==============================] - 1s 142us/step - loss: 0.3645 - acc: 0.8456
Epoch 69/100
7500/7500 [==============================] - 1s 142us/step - loss: 0.3632 - acc: 0.8449
Epoch 70/100
7500/7500 [==============================] - 1s 146us/step - loss: 0.3622 - acc: 0.8440
Epoch 71/100
7500/7500 [==============================] - 1s 149us/step - loss: 0.3617 - acc: 0.8445
Epoch 72/100
7500/7500 [==============================] - 1s 144us/step - loss: 0.3609 - acc: 0.8455
Epoch 73/100
7500/7500 [==============================] - 1s 142us/step - loss: 0.3601 - acc: 0.8472
Epoch 74/100
7500/7500 [==============================] - 1s 144us/step - loss: 0.3582 - acc: 0.8488
Epoch 75/100
7500/7500 [==============================] - 1s 136us/step - loss: 0.3579 - acc: 0.8513
Epoch 76/100
7500/7500 [==============================] - 1s 138us/step - loss: 0.3566 - acc: 0.8537
Epoch 77/100
7500/7500 [==============================] - 1s 142us/step - loss: 0.3559 - acc: 0.8543
Epoch 78/100
7500/7500 [==============================] - 1s 142us/step - loss: 0.3558 - acc: 0.8565
Epoch 79/100
7500/7500 [==============================] - 1s 141us/step - loss: 0.3553 - acc: 0.8553
Epoch 80/100
7500/7500 [==============================] - 1s 144us/step - loss: 0.3550 - acc: 0.8572
Epoch 81/100
7500/7500 [==============================] - 1s 154us/step - loss: 0.3536 - acc: 0.8605 0s - loss: 0.3563 - acc:
Epoch 82/100
7500/7500 [==============================] - 1s 173us/step - loss: 0.3526 - acc: 0.8581
Epoch 83/100
7500/7500 [==============================] - 1s 164us/step - loss: 0.3529 - acc: 0.8589
Epoch 84/100
7500/7500 [==============================] - 1s 161us/step - loss: 0.3525 - acc: 0.8597
Epoch 85/100
7500/7500 [==============================] - 1s 161us/step - loss: 0.3520 - acc: 0.8600
Epoch 86/100
7500/7500 [==============================] - 1s 161us/step - loss: 0.3517 - acc: 0.8613
Epoch 87/100
7500/7500 [==============================] - 1s 160us/step - loss: 0.3522 - acc: 0.8609
Epoch 88/100
7500/7500 [==============================] - 1s 157us/step - loss: 0.3506 - acc: 0.8599
Epoch 89/100
7500/7500 [==============================] - 1s 159us/step - loss: 0.3503 - acc: 0.8619
Epoch 90/100
7500/7500 [==============================] - 1s 155us/step - loss: 0.3497 - acc: 0.8595
Epoch 91/100
7500/7500 [==============================] - 1s 166us/step - loss: 0.3506 - acc: 0.8603
Epoch 92/100
7500/7500 [==============================] - 1s 159us/step - loss: 0.3490 - acc: 0.8617
Epoch 93/100
7500/7500 [==============================] - 1s 163us/step - loss: 0.3485 - acc: 0.8628
Epoch 94/100
7500/7500 [==============================] - 1s 159us/step - loss: 0.3498 - acc: 0.8619
Epoch 95/100
7500/7500 [==============================] - 1s 156us/step - loss: 0.3484 - acc: 0.8631
Epoch 96/100
7500/7500 [==============================] - 1s 163us/step - loss: 0.3475 - acc: 0.8624
Epoch 97/100
7500/7500 [==============================] - 1s 162us/step - loss: 0.3470 - acc: 0.8647
Epoch 98/100
7500/7500 [==============================] - 1s 158us/step - loss: 0.3474 - acc: 0.8655
Epoch 99/100
7500/7500 [==============================] - 1s 154us/step - loss: 0.3469 - acc: 0.8612
Epoch 100/100
7500/7500 [==============================] - 1s 155us/step - loss: 0.3469 - acc: 0.8635

In [40]:
#predict the result of the test results 
predicted_y = nn_classifier.predict(test_X)
predicted_y =  (prediction > 0.5)
predicted_y

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [42]:
from sklearn.metrics import precision_score, \
    recall_score, confusion_matrix, classification_report, \
    accuracy_score, f1_score

print('Accuracy:', accuracy_score(test_y, predicted_y))
print('F1 score:', f1_score(test_y, predicted_y))
print('Recall:', recall_score(test_y, predicted_y))
print('Precision:', precision_score(test_y, predicted_y)) 
print ('\n clasification report:\n', classification_report(test_y,predicted_y))
print('\n confussion matrix:\n',confusion_matrix(test_y, predicted_y))

Accuracy: 0.8548
F1 score: 0.5997794928335171
Recall: 0.5343811394891945
Precision: 0.6834170854271356

 clasification report:
              precision    recall  f1-score   support

          0       0.89      0.94      0.91      1991
          1       0.68      0.53      0.60       509

avg / total       0.85      0.85      0.85      2500


 confussion matrix:
 [[1865  126]
 [ 237  272]]

https://stats.stackexchange.com/questions/154879/a-list-of-cost-functions-used-in-neural-networks-alongside-applications

http://neuralnetworksanddeeplearning.com/about.html

https://iamtrask.github.io/2015/07/27/python-network-part2/